# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

within_d <- function(id, x, y, x_ref, y_ref, max_distance) {
    .Call('withinD_within_d', PACKAGE = 'withinD', id, x, y, x_ref, y_ref, max_distance)
}

